version: "3.9"

services:
  redis:
    image: redis/redis-stack
    ports:
      - '6379:6379'

  fastapi_app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - csv_file_path=../data/vehicletest.csv
      - parquet_file_path=../data/vehicletest.parquet
      - JWT_SECRET_KEY=fsufewrghjbejhgbdsughwieguEWKGJNSKGJSNGIJWSEOWHUGIWEUHGSDKJGFNWSEKGJUHEW242563YwegWTY43
      - JWT_REFRESH_SECRET_KEY=fsufewrghjbejhgbdsughwieguEWKGJNSKGJSNGIJWSEOWHUGIWEUHGSDKJGFNWSEKGJUHEW242563YwegWTY43
    restart: always
    depends_on:
      - redis
